### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by AgIt0**
It's a web app :)

### CODE REVIEW

**Comment by gsamokovarov** [comment]
:(

**Comment by AgIt0** [comment]
:(

**Comment by gsamokovarov** [comment]
Actually, my intuition was correct here. Its `an` because `web` is pronounced with vowel first. Its the same with [`an hour`](https://answers.yahoo.com/question/index?qid=20061107183737AAh5R7R).

**Comment by AgIt0** [comment]
Yes, but [hour](http://www.merriam-webster.com/dictionary/hour) begins with a vowel sound, while [web](http://www.merriam-webster.com/dictionary/web) begins with a consonant sound(I think it's considered smth like consonant glide, look at what you made me research :D) And according to [google books](https://books.google.com/ngrams/graph?content=a+web%2Can+web&case_insensitive=on&year_start=1940&year_end=2015&corpus=15&smoothing=3&share=&direct_url=t4%3B%2Ca%20web%3B%2Cc0%3B%2Cs0%3B%3Ba%20Web%3B%2Cc0%3B%3Ba%20web%3B%2Cc0%3B%3BA%20Web%3B%2Cc0%3B%3BA%20web%3B%2Cc0%3B.t4%3B%2Can%20web%3B%2Cc0%3B%2Cs0%3B%3Ban%20Web%3B%2Cc0%3B%3Ban%20web%3B%2Cc0) it's used quite a bit more

**Comment by gsamokovarov** [comment]
Yup, that's true. Did the same research after the revert when 364b2d8844e58b5951ee519c6e40b30cdded332a popped out :sweat_smile:

Work arounds instead of problem solving, ftw!

**Comment by AgIt0** [comment]
Sound better that way :D

**Pull request merged**
